import pygame as pg

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARK_GRAY = (30, 30, 30)

TOP_BAR_HEIGHT = 80
BOTTOM_BAR_HEIGHT = 80

# Define the playable area
GAME_TOP = TOP_BAR_HEIGHT
GAME_BOTTOM = WINDOW_HEIGHT - BOTTOM_BAR_HEIGHT
GAME_LEFT = 0
GAME_RIGHT = WINDOW_WIDTH